#ifndef SPRITEVIEWER_UI_WXSPRITEVIEWER_H
#define SPRITEVIEWER_UI_WXSPRITEVIEWER_H

#include "ui/wx/wxInclude.h"

enum wxIdentifier
{
	wxID_CUSTOM_LOWEST = wxID_SHARED_HIGHEST + 1,

	wxID_MAINWND_LOADSPRITE,
	wxID_MAINWND_LOADBACKGROUND,
	wxID_MAINWND_SAVESPRITE,

	wxID_MAINWND_TAKESCREENSHOT,
	wxID_MAINWND_DUMPSPRITEINFO,
	wxID_MAINWND_TOGGLEMESSAGES,

	wxID_MAIN_PAGECHANGED,

	wxID_CUSTOM_HIGHEST
};

#define SPRITEVIEWER_TITLE "Half-Life Sprite Viewer"
#define SPRITEVIEWER_SETTINGS_FILE "SpriteViewerSettings.txt"
#define SPRITEVIEWER_DUMP_SPRITE_INFO_FILE "sprifile.txt"

#endif //SPRITEVIEWER_UI_WXSPRITEVIEWER_H